INSERT INTO USER (USERNAME, PASSWORD) VALUES ('karthiga', '$2a$11$BY0gUDJ0TNm0b0fd7Hx0J.PGJBy2ishtIXiQmhS0NU1o5XKvvdUgq');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('guest', '$2a$11$czUYSb7eCOT6mZAaS9GvWesxr6ip.CnuZKDlRkMKHV3Rq0eiJ1k9.');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('karthiga', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('karthiga', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('guest', 'USER');